name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      # Run build to make sure it works
      - name: Run build
        run: bun run build

      - name: Check executable
        run: ./dist/aica help

      - name: Build docker image
        run: docker build -f Dockerfile.github_actions -t aica .
